# Generated by Django 5.2.10 on 2026-02-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlogmodel",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
